#to run this use vars.yml and inventory.ini

- name: Start Local Registry
  hosts: target_group
  become: true
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Run local Docker Registry
      docker_container:
        name: local_registry
        image: registry:latest
        ports:
          - "5000:5000"
        restart_policy: always
        volumes:
          - "{{ registry_data_directory }}:/var/lib/registry"